production:
  sessions:
    default:
      database: peas
      hosts:
        - localhost:27017

development:
  sessions:
    default:
      database: peas_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: peas_test
      hosts:
        - localhost:27017